### ISSUE TITLE
How to mock actions inside other actions?

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera-testsuite#4] opened 2017-09-13 20:20 UTC
I have this mongo actions inside user-save action:

```
//Here are 2 actions one inside another
hemera.act({
                    topic: 'mongo-store',
                    cmd: 'find',
                    collection: 'users',
                    query: { email: userPeyload.email }
                }, (err: Error, resp: any) => {

                    if (err) {
                        done(err);
                    }
                    
                    
                    if (resp.result.length === 0) {
                        hemera.act({
                            topic: 'mongo-store',
                            cmd: 'create',
                            collection: 'users',
                            data: user
                        }, (err: Error, resp: any) => {
                            if (err) {
                                done(null, err);
                            }

                            //TODO: call mail service here
                            done(null, 'We sent you activation link to the mail.');
                        })

                    } else {
                        const UnauthorizedError = hemera.createError("Unauthorized");
                        const mess = new UnauthorizedError("User already exists.");
                        done(mess);
                    }
                })
```

Stub for first works but for second inside not...

```
actStub.stub({
                topic: 'mongo-store',
                cmd: 'find',
                collection: 'users',
                query: { email: "vladimir@some.com" }
            }, null, {result: []});


actStub.stub({
                topic: 'mongo-store',
                cmd: 'create',
                collection: 'users',
                data: userData
            }, null, 50);
```

**Comment by StarpTech** [comment] 2017-09-14 09:11
Hi @vforv thanks for reporting. At the moment stubs only working with fixed pattern the problem is `data: userData`. We use sinonjs to do the job. I think the stubbing process can be improved by [custom matchers](http://sinonjs.org/releases/v3.2.1/matchers/#sinonmatchany) feel free to try something and create a PR.

**Comment by vforv** [comment] 2017-09-14 14:24
Hi, @StarpTech I have the same problem even when I put static data like this: `data:'something'`...

**Comment by StarpTech** [comment] 2017-09-15 13:32
Mocking only this works right? 
```
actStub.stub({
                topic: 'mongo-store',
                cmd: 'create',
                collection: 'users'
                data: 'test'
            }, null, 50);

hemera.act({
                            topic: 'mongo-store',
                            cmd: 'create',
                            collection: 'users',
                            data: 'test'
})
```
Your stub has to be fixed.

**Comment by StarpTech** [comment] 2017-09-15 13:35
We have to use `sinon.match({ author: "cjno" })` instead `this.s.withArgs(pattern)` I will prepare a PR.

**Comment by StarpTech** [comment] 2017-09-15 13:39
I will evaluate your case but can take some time.

**Comment by StarpTech** [comment] 2017-09-15 14:24
We use now the same router as in hemera for the stub match. Released with 1.3.0

**Comment by vforv** [comment] 2017-09-15 15:07
Hi @StarpTech , I still getting timeout error and action inside never runs...

**Comment by StarpTech** [comment] 2017-09-15 15:10
Hi, please provide a sample repo or simple snippet so that I can reproduce it. Try to abstract the error in a single test.

**Comment by veeramarni** [comment] 2017-09-15 15:13
`test file`
```
'use strict';

const Hemera = require('nats-hemera');
const Plugin1 = require('./example-async');
const HemeraTestsuite = require('hemera-testsuite');


// prevent warning message of too much listeners
process.setMaxListeners(0);

describe('hemera-testPlugin', function () {
    const PORT = 4222;
    const topic = 'testPlugin';
    let server;

    // Start up our own nats-server
    beforeAll(function (done) {
        server = HemeraTestsuite.start_server(PORT, done);
    });

    // Shutdown our server after we are done
    afterAll(function (done) {
        server.kill();
        done();
    });

    it('Should be able to add two numbers', function (done) {
        const nats = require('nats').connect();
        const options = { a: 1 };
        const hemera = new Hemera(nats, {
            logLevel: 'info',
        });
        hemera.use(Plugin1, options);

        hemera.ready(() => {
            hemera.ext('onServerPreRequest', async function (ctx, req, res) {
                await Promise.resolve();
            });

            hemera.act({
                topic,
                cmd: 'add',
                a: 1,
                b: 20,
            }, async function (err, resp) {
                try {
                    await resp;
                    expect(err).toBeNull();
                    expect(resp.result).toEqual(21);
                    hemera.close(done);
                } catch (err) {
                    hemera.close(done.fail);
                }

            });
        });

    });
});
```

`Test Async plugin`

```
'use strict';

const Hp = require('hemera-plugin');

exports.plugin = Hp(function hemeraTestPlugin(options, next) {
    const hemera = this;
    const topic = 'testPlugin';
    this.log.info('received options (%j)', options);
    hemera.add({
        topic,
        cmd: 'add',
    }, async function (req) {
        const result = await Promise.resolve({
            result: req.a + req.b,
        });
        return result;
    });

    next();
});

exports.options = {};

exports.attributes = {
    pkg: require('../../package.json'),
};
```

**Comment by vforv** [comment] 2017-09-15 15:15
Okay here is the action:

this.hemera.add({
            topic: 'user',
            cmd: 'login'
        }, login.userCredentials)

`login.userCredentials` function:

```
public userCredentials(msg: any, done: any): any {
        let __this: any = this;
        let hemera: T = __this;

        hemera.act({
            topic: 'user-credentials',
            cmd: 'verify',
            email: msg.email,
            password: msg.password
        }, (err: Error, user: any) => {
            if (err) {
                done(err)
            }
            
            if (!user) {
                const UnauthorizedError = hemera.createError("Unauthorized");
                const mess = new UnauthorizedError("User credentials not valid.");
                done(mess);
            }

            hemera.act({
                topic: 'jwt',
                cmd: 'generate',
                userId: user._id
            }, (err: Error, resp: any) => {
                if (err) {
                    done(err)
                }

                done(null, { token: resp })
            });

        });
    }
```

And here is the test I am trying to run:

```
 L.test('Login user test', (done) => {
        const nats = new Nats()
        const hemera = new Hemera(nats, {
            logLevel: 'info'
        })
        const login = new LoginActions(hemera)

        const actStub = new ActStub(hemera);
        hemera.ready(() => {
            //add actions
            login.getLoginAction();

            actStub.stub({
                topic: 'user-credentials',
                cmd: 'verify',
                email: 'vladimir@some.com',
                password: 'test123'
            }, null, {});

            actStub.stub({
                topic: 'jwt',
                cmd: 'generate',
                userId: '123'
            }, null, {token: 'token'});

            //run test
            AddStub.run(hemera, { topic: 'user', cmd: 'login' }, { email: 'vladimir@some.com', passowrd: 'test123' }, function (err: any, result: any) {

                console.log(result)
                done()
            })

        });
    });
```

So I am trying to stub this 2 actions inside the function...

**Comment by StarpTech** [comment] 2017-09-15 15:22
@vforv where is your server method with pattern `{ topic: 'user', cmd: 'login' }` ? `AddStub.run` will execute your method with the specific arguments.

**Comment by vforv** [comment] 2017-09-15 15:25
First code snippet:
```
this.hemera.add({
            topic: 'user',
            cmd: 'login'
        }, login.userCredentials)
```

It is called after hemera ready in test:
`login.getLoginAction();`

**Comment by StarpTech** [comment] 2017-09-15 15:36
Try to move the stub for `topic:jwt` before the `topic: user-credentials` stub.

```
      actStub.stub({
                topic: 'jwt',
                cmd: 'generate',
                userId: '123'
            }, null, {token: 'token'});
```

**Comment by vforv** [comment] 2017-09-15 15:45
I tried but still jwt action not run... Getting timeout error...

**Comment by StarpTech** [comment] 2017-09-15 15:48
Please provide a working example. I can't identify the issue with the current information.

**Comment by vforv** [comment] 2017-09-15 16:39
Here is working example:
https://github.com/vforv/hemera-error

**Closed** 2017-09-15 19:43 UTC
